# Generated by Django 2.2 on 2019-09-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Venuename', max_length=200),
        ),
    ]
