# Generated by Django 2.2 on 2019-10-01 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0006_auto_20190925_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='host',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='account',
            name='host',
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
